logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: usu
    password: pass
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog.yaml
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  error:
    whitelabel:
      enabled: false
server:
  error:
    whitelabel:
      enabled: false


